name: Build and publish

on:
  repository_dispatch:
    types: [all]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Fetch posts data from tumblr
      run: |
        npm install
        npm run env
      env:
        BLOG_IDENTIFIER: ${{ secrets.BLOG_IDENTIFIER }}
        BLOG_API_KEY: ${{ secrets.BLOG_API_KEY }}
